---
abstract: unknown
author:
  - 'Rajkumar Reddy'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lang-HL
no_index:
  directory:
    - t
    - inc
requires:
  Data::Printer: '0'
  Lang::HL::Export: '0'
  Perl::Tidy: '0'
  Regexp::Grammars: '0'
version: '5.054'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
